config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do

  resources :projects do
    resources :comments
  end
  
  resources :users do
  	resources :comments
  end

 
  resources :sessions, only: [:new, :create, :destroy]
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  root to:'projects#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true
class Comment < ApplicationRecord
  validates_presence_of :content
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
# frozen_string_literal: true
class Project < ApplicationRecord

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/ unless Rails.env.test?
	belongs_to :user
	validates :name, uniqueness: true, presence: true
	has_many :comments, dependent: :destroy
	
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
	has_secure_password
	validates_length_of :name, minimum:4
	validates_presence_of :password, :email
	validates_length_of :password, minimum: 6
	validates_confirmation_of :password
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }, uniqueness: true
	has_many :projects
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :authenticate_user
	helper_method :current_user, :has_edit_permission?, :is_admin?, :is_banned

	def current_user
		@current_user ||= User.find(user_id) if user_id
	end

	private
	
	def has_edit_permission?
		if current_user != project.user
			flash.alert = 'Permission denied!!!'
			@current_user.update_attribute(:banned, true)
			redirect_to log_out_path
		end
	end

	def is_admin?
		@current_user.admin
	end
	
	def user_id
		session[:user_id]
	end

	def logged_in
		current_user.present?
	end

	def authenticate_user
		return if logged_in
		redirect_to new_session_path
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	 
	def new
		@comment = project.comments.build
	end

	def create
		@comment = project.comments.build(comments_params)
		@comment.user = current_user
		if @comment.save
			redirect_to project_path(@project)
		else
			render :new
		end
	end

	def edit
		comment
	end

	def update
		if comment.update(comments_params)
			redirect_to project_path(@project)
		else
			render :edit
		end
	end

	def destroy
		comment.destroy
		redirect_to project_path(project)
	end    
		
	private

	def comments_params
		params.require(:comment).permit(:content, :rating)
	end

	def project
		@project ||= Project.find(params[:project_id])
	end

	def comment
		@comment ||= project.comments.find(params[:id])
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :has_edit_permission?, only: [:edit, :update, :destroy]
	before_action :project, only: :show
	
	def index
		@projects = Project.all.order(:id).page(params[:page]).per(5)
	end

	def show
		#project
		@avg_rating ||= commentz.blank? ? 0 : commentz.average(:rating).round(2)
		@comments = @commentz.order("updated_at DESC").page(params[:page]).per(5)		
	end

	def new
		@project = Project.new
	end

	def create
		@project = current_user.projects.build(project_params)
		if @project.save
			redirect_to projects_path, notice: 'Project was created'
		else
			render :new
		end
	end

	def edit
		project
	end

	def update
		if project.update(project_params)
			redirect_to project_path, notice: 'Project was successfully updated.'
		else
			render :edit
		end
	end

	def destroy
		project.destroy
		redirect_to projects_path, notice: 'Project was successfully destroyed.'
	end

	private

	def commentz
		@commentz ||= @project.comments
	end

	def project
		@project ||= Project.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:name, :image, :description)
	end

end

app/controllers/raiting_controller.rb
class RatingsController < ApplicationController

  def update
    @rating = Rating.find(params[:id])
    @comment = @rating.comment
    if @rating.update_attributes(score: params[:score])
      respond_to do |format|
        format.js
      end
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :authenticate_user, only: [:new, :create]
	before_action :current_user

	def new
	end

	def create

		user = User.find_by_email(params[:email])&.authenticate(params[:password])
		if user
			session[:user_id] = user.id
			current_user
			# binding.pry
			if is_banned
				destroy
				flash[:error] = "This account has been suspended" 
			else
				redirect_to root_url, notice: 'Logged in!'
			end
		else
			flash.now.alert = 'Invalid email or password'
			render :new
		end

	end

	def destroy
		session.delete(:user_id)
		redirect_to root_url, notice: 'Logged out!'
	end

	private

	def is_banned
		@current_user.present? && @current_user.banned
	end

end

app/controllers/users_controller.rb
# frozen_string_literal: true
class UsersController < ApplicationController
	skip_before_action :authenticate_user, only: [:new, :create]
	helper_method :is_admin?

	def index
		@users = User.all.order(:name)
		if is_admin?
			@users
		else
			redirect_to users_path
		end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			UserMailer.welcome_email(@user).deliver_now
			redirect_to new_session_path#, notice: 'Successfully signed up! You can log in now :)'
		else
			# flash[:notice] = "Something went wrong!"
			render :new
		end
	end

	def destroy
		# binding.pry
		user.destroy
		redirect_to users_path, notice: "You just delete #{user.name}'s account"
	end

	private

	def user
		@user ||= User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
end

app/views/comments/edit.html.erb
<header>
	<h1>Edit Comment</h1>	
</header>
<main>
	<%= form_for [@project, @comment], html: { multipart: true } do |f| %>
		<div class="label">			
			<%= f.label :Rating %>
		</div>
		<div id="star-rating" data-score="<%= @comment.rating %>"></div>
	  <div class="label">			
			<%= f.label :"content:" %>
		</div>
	  <div class="description">
	  	<%= f.text_area :content, size: "70x10", placeholder: "Content" %>
		</div>
		<%= f.submit %>
	<% end %>
	<div class="Back">
		<%= link_to 'Cancel', :back %>
	</div>
</main>
<script>
$('#star-rating').raty({    
    path: '/assets/',
    score: function(){
      return $(this).atrr('data-score');
    }, 
    scoreName: 'comment[rating]'
  });
</script>

app/views/comments/edit.html.haml
%header
	%h1 Edit Comment
%main
	= form_for [@project, @comment], html: { multipart: true } do |f|
		.label
			= f.label :Rating
		#star-rating{"data-score" => @comment.rating}
		.label
			= f.label :"content:"
		.description
			= f.text_area :content, size: "70x10", placeholder: "Content"
		= f.submit
	.Back
		= link_to 'Cancel', :back
:javascript
	$('#star-rating').raty({    
			path: '/assets/',
			score: function(){
				return $(this).atrr('data-score');
			}, 
			scoreName: 'comment[rating]'
		});

app/views/comments/new.html.erb
<header>
	<h1>New Comment</h1>	
</header>
<main>
	<%= form_for [@project, @comment], html: { multipart: true } do |f| %>
		<div id="star-rating"></div>
		<div class="description">
			<%= f.text_area :content, size: "70x5", placeholder: "Content" %>
		</div>		
			<%= f.submit %>
	<% end %>
	<div class="Back">
		<%= link_to 'Cancel', project_path(@project) %>
	</div>	
</main>
<script>
$('#star-rating').raty({    
	path: '/assets/',
	score: 3 , 
	scoreName: 'comment[rating]'
	});
</script>

app/views/comments/new.html.haml
%header
	%h1 New Comment
%main
	= form_for [@project, @comment], html: {multipart: true} do |f|
		#star-rating
		.description
			= f.text_area :content, size: "70x5", placeholder: "Content"
		= f.submit
		.Back
			= link_to 'Cancel', project_path(@project)
:javascript
	$('#star-rating').raty
	({    
		path: '/assets/',
		score: 3 , 
		scoreName: 'comment[rating]'
	});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proj</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="user_nav">
  		<% if current_user %>
    		Logged in as <span style="text-decoration: underline;"><%= current_user.name %></span>
        <%= link_to "Log out", log_out_path %>
  		<% else %>
    		<%= link_to "Sign up", new_user_path %> or
    		<%= link_to "Sign in", new_session_path %>
  		<% end %>
    </div>

    <% flash.each do |name, msg| %>
  		<%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

    <%= yield %>
    
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Proj
		= csrf_meta_tags
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
	%body
		#user_nav
			- if current_user
				Logged in as
				%span{ style: "text-decoration: underline;"}= current_user.name
				= link_to "Log out", log_out_path
			- else
				= link_to "Sign up", new_user_path
				or
				= link_to "Sign in", new_session_path
		- flash.each do |name, msg|
			= content_tag :div, msg, id: "flash_#{name}"
		= yield
		%footer 
			This site was created by
			%a{ href: "https://github.com/PolkowskiA", target: "_blank"}PolkowskiA

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proj</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="turbolinks-cache-control" content="no-cache">
  </head>

  <body>

    <div id="user_nav">
  		<% if current_user %>
    		Logged in as <span style="text-decoration: underline;"><%= current_user.name %></span>
        <%= link_to "Log out", log_out_path %>
  		<% else %>
    		<%= link_to "Sign up", new_user_path %> or
    		<%= link_to "Sign in", new_session_path %>
  		<% end %>
    </div>

    <% flash.each do |name, msg| %>
  		<%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

    <%= yield %>
    
  </body>
</html>

app/views/projects/edit.html.erb
<header>

	<h1>Edit project</h1>

</header>

<main>

	<%= form_for @project, html: { multipart: true } do |f| %>

		<div class="label">
			
			<%= f.label :"Title:" %>

		</div>

		<div class="name">
		
	  	<%= f.text_field :name, placeholder: "Title" %>

	  </div>

	  <div class="label">
			
			<%= f.label :"Description:" %>

		</div>

	  <div class="description">

	  	<%= f.text_area :description, size: "70x10", placeholder: "Description (optional)" %>

		</div>

	  <div class="addImage">

	  	<div class="label">

		  	<%= f.label :"Update image:" %>

			</div>

		  <div class="fileField">

		 		<%= f.file_field :image %>

		 	</div>

		</div>

		<%= f.submit %>

	<% end %>

	<div class="Back">

		<%= link_to 'Cancel', request.referer %>

	</div>

</main>

app/views/projects/edit.html.haml
%header
	%h1 Edit Project
%main
	= form_for @project, html: {multipart: true } do |f|
		.label
			= f.label :"Title"
		.name
			= f.text_field :name, placeholder: "Title"
		.label
			= f.label :"Description"
		.description
			= f.text_area :description, size: "70x10", placeholder: "Description (optional)"
		.addImage
			.label
				=f.label :"Update image"
			.fileField
				= f.file_field :image
		= f.submit
	.Back
		= link_to 'Cancel', request.referer

app/views/projects/edit2.html.erb
<header>
	<h1>Edit project</h1>
</header>
<main>
	<%= form_for @project, html: { multipart: true } do |f| %>
		<div class="label">			
			<%= f.label :"Title:" %>
		</div>
		<div class="name">		
	  	<%= f.text_field :name, placeholder: "Title" %>
	  </div>
	  <div class="label">			
			<%= f.label :"Description:" %>
		</div>
	  <div class="description">
	  	<%= f.text_area :description, size: "70x10", placeholder: "Description (optional)" %>
		</div>
	  <div class="addImage">
	  	<div class="label">
		  	<%= f.label :"Update image:" %>
			</div>
		  <div class="fileField">
		 		<%= f.file_field :image %>
		 	</div>
		</div>
		<%= f.submit %>
	<% end %>
	<div class="Back">
		<%= link_to 'Cancel', request.referer %>
	</div>
</main>

app/views/projects/index.html.erb
<div class="container">
  <header>

    <h1>Projects</h1>
  
  </header>  

  <div class="content">

    <div class="project">

      <% if @projects.present? %>

        <% @projects.each do |project| %>

          <div class="project_container">

            <div class="project_view">

              <%= link_to project.name, project %>

            </div>

            <div class="image">
        
              <%= image_tag project.image.url("thumb") %>

            </div>

            <div class="starRating" data-score="<%= project.comments.average(:rating) %>"></div>

            <% if project.user == current_user %>

              <div class="list">
                
                <i class="icon-list-bullet"></i>    

                <ul>

                  <li>
                    <%= link_to edit_project_path(project) do %>

                      Edit

                    <% end %>
                  </li>

                  <li>
                    <%= link_to project, method: :delete, data: { confirm: "Project:     '#{project.name}'     will be removed. Are you sure?" } do %>

                      Delete

                    <% end %>

                  </li>

                </ul>

              </div>

            <% end %>

            <div style="clear: both;"></div>

            <div class="project_data">
              
              Created by: <%= project.user.name %>
              at: <%= project.created_at.strftime('%Y-%m-%d') %>

            </div>

          </div>

          <% end %>

        <% else %>

           No Projects Found

        <% end %>

    </div>

    <div class="creator">

      <%= link_to new_project_path do %>

        <i class="icon-plus-squared"></i>

      <% end %>

    </div>

    <div style="clear: both;"></div>

  </div>

  <%= paginate @projects %>
  
  <footer>This site was created by <a href="https://github.com/PolkowskiA" target="_blank">PolkowskiA</a>. All rights reserved &copy; 2018</footer>
</div>

<script>

$('.starRating').raty({
    readOnly: true,
    path: '/assets/',
    score: function(){
      return $(this).atrr('data-score');
    }
  });
</script>

app/views/projects/index.html.haml
%header
	%h1 Projects
- if is_admin?
	.admin_panel
		= link_to users_path do
			Admin Panel		
.main_projects_container
	.projects_list
		- if @projects.present?
			- @projects.each do |project|
				.project_container
					.project_name
						= link_to project.name, project
					.project_image
						= image_tag project.image.url("thumb")
					.star-rating#index{:"data-score"=> project.comments.average(:rating)}				
					- if project.user == current_user
						.list
							%i.icon-list-bullet
							%ul
								%li
									= link_to edit_project_path(project) do
										Edit
								%li
									= link_to project, method: :delete, data: { confirm: "Project:     '#{project.name}'     will be removed. Are you sure?" } do
										Delete
					%div{style: 'clear: both;'}
					.project_data
						Created by #{project.user.name} at: #{ project.created_at.strftime('%Y-%m-%d')}
		- else
			Not Project Found
	.creator
		= link_to	new_project_path do
			%i.icon-plus-squared
= paginate @projects

app/views/projects/index2.html.erb
<div class="container">
  <header>
    <h1>Projects</h1>  
  </header>  
  <div class="content">
    <div class="project">
      <% if @projects.present? %>
        <% @projects.each do |project| %>
          <div class="project_container">
            <div class="project_view">
              <%= link_to project.name, project %>
            </div>
            <div class="image">        
              <%= image_tag project.image.url("thumb") %>
            </div>
            <div class="starRating" data-score="<%= project.comments.average(:rating) %>"></div>
            <% if project.user == current_user %>
              <div class="list">                
                <i class="icon-list-bullet"></i>
                <ul>
                  <li>
                    <%= link_to edit_project_path(project) do %>
                      Edit
                    <% end %>
                  </li>
                  <li>
                    <%= link_to project, method: :delete, data: { confirm: "Project:     '#{project.name}'     will be removed. Are you sure?" } do %>
                      Delete
                    <% end %>
                  </li>
                </ul>
              </div>
            <% end %>
            <div style="clear: both;"></div>
            <div class="project_data">              
              Created by: <%= project.user.name %>
              at: <%= project.created_at.strftime('%Y-%m-%d') %>
            </div>
          </div>
          <% end %>
      <% else %>
           No Projects Found
      <% end %>
    </div>
    <div class="creator">
      <%= link_to new_project_path do %>
        <i class="icon-plus-squared"></i>
      <% end %>
    </div>
    <div style="clear: both;"></div>
  </div>
  <%= paginate @projects %>  
  <footer>This site was created by <a href="https://github.com/PolkowskiA" target="_blank">PolkowskiA</a>. All rights reserved &copy; 2018</footer>
</div>
<script>
$('.starRating').raty({
    readOnly: true,
    path: '/assets/',
    score: function(){
      return $(this).atrr('data-score');
    }
  });
</script>

app/views/projects/new.html.erb
<header>

	<h1>New Project</h1>

</header>

<main>

	<%= form_for [@project], html: { multipart: true } do |f| %>

		<div class="name">
		
	  	<%= f.text_field :name, placeholder: "Title" %>

	  </div>

	  <div class="description">

	  	<%= f.text_area :description, size: "70x10", placeholder: "Description (optional)" %>

		</div>

	  <div class="addImage">

	  	<div class="label">

		  	<%= f.label :"Add image" %>

			</div>

		  <div class="fileField">

		 		<%= f.file_field :image %>

		 	</div>

		</div>

		<%= f.submit %>

	<% end %>

	<div class="Back">

		<%= link_to 'Cancel', projects_path %>

	</div>

</main>

app/views/projects/new.html.haml
%header
	%h1 New Project
%main
	= form_for @project, html: {multipart: true } do |f|
		.name
			= f.text_field :name, placeholder: "Title"
		.description
			= f.text_area :description, size: "70x10", placeholder: "Description(optional)"
		.addImage
			.label
				= f.label :"AddImage"
			.fileField
				= f.file_field :image
		= f.submit
	.Back
		= link_to 'Cancel', projects_path

app/views/projects/new2.html.erb
<header>
	<h1>New Project</h1>
</header>
<main>
	<%= form_for [@project], html: { multipart: true } do |f| %>
		<div class="name">		
	  	<%= f.text_field :name, placeholder: "Title" %>
	  </div>
	  <div class="description">
	  	<%= f.text_area :description, size: "70x10", placeholder: "Description (optional)" %>
		</div>
	  <div class="addImage">
	  	<div class="label">
		  	<%= f.label :"Add image" %>
			</div>
		  <div class="fileField">
		 		<%= f.file_field :image %>
		 	</div>
		</div>
		<%= f.submit %>
	<% end %>
	<div class="Back">
		<%= link_to 'Cancel', projects_path %>
	</div>
</main>

app/views/projects/show.html.erb
<div class="headerShowProj">

  <div class="showHeaderTop">

        <div class="title">
          
          <h1>Title:</h1>

        </div>

        <% if current_user == @project.user %> 

            <%= link_to @project, method: :delete, data: { confirm: "Project:    '#{@project.name}'       will be removed. Are you sure?" } do %>

              <div class="showIcon">
                
                <i class="icon-trash"></i> 

              </div>

            <% end %>

            <%= link_to edit_project_path(@project) do %>             

              <div class="showIcon">
                
                <i class="icon-pencil-1"></i>

              </div>

            <% end %>

            <div style="clear: both;"></div>              

        <% end %>

  </div>

  <div class="showName">

      <p><%= @project.name %></p>

  </div>

  <div class="star-rating" data-score="<%= @avg_rating %>"></div> 

  <em><%= "#{@avg_rating}/5 of #{@commentz.size} comments"%> </em>

  <div class="showHeaderBottom">  

    <div class="showBack">

        <%= link_to 'Back', projects_path %>

    </div>

    <div class="showCreate">

      Created by: <%= @project.user.name %>

    </div>

    <div style="clear: both;"></div>

  </div>

</div>

<div class="contentShowProj">
  
  <div class="showImage">
    
    <%= image_tag @project.image.url("medium") %>

  </div>

  <div class="showArticle">    

    <%= simple_format(@project.description) %>      

  </div> 

  <div style="clear: both; "></div>   

</div>

<div class="commentsShowProj">
  
  <div class="commentsHeader">
    
    <div class="titleComments">

      <h2> Comments </h2>

    </div>

    <div class="creator" id="show">

      <%= link_to new_project_comment_path(@project) do %>

        <i class="icon-plus-squared"></i>

      <% end %>

    </div>

    <div style="clear: both;"></div>

  </div>

  <div class="commentsContent">

    <% if @comments.present? %>

      <% @comments.each do |comment| %>

        <div class="comment">

          <div class="commentTop">

            <div class="commentAuthor">

              <%= comment.user.name %>
                
              </div>
            <div class="commentTimeStamps">

              <%= comment.created_at.strftime('%d-%b-%Y at: %T')%>

            </div>

            <div class="commentRating" data-score="<%= comment.rating %>"></div> 

            <% if comment.user == current_user %> 

              <%= link_to project_comment_path(@project, comment), method: :delete, data: {confirm: 'Are y sure ?'} do %>

                <div class="commentIcon">

                  <i class="icon-trash"></i>

                </div>

              <% end %>

              <%= link_to edit_project_comment_path(@project, comment) do %>

                <div class="commentIcon"><i class="icon-pencil-1"></i></div>

              <% end %>

            <% end %>

          </div>

          <div class="commentBottom">
            
            <%= simple_format(comment.content) %>

          </div>

        </div>        

        <div style="clear: both;"></div>

      <% end %>         

    <% else %>

    Be the first one. Comment Now!

    <% end %>
    
    <%= paginate @comments %>
  </div>


  </div>

</div>

<footer>
  This site was created by <a href="https://github.com/PolkowskiA" target="_blank">PolkowskiA</a>. All rights reserved &copy; 2016
</footer>

<script>

  $('.star-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function(){
      return $(this).atrr('data-score');
    }
  });
       
  $('.commentRating').raty({
    readOnly: true,
    path: '/assets',
    score: function(){
      return $(this).atrr('data-score');
    }
  });

</script>

app/views/projects/show.html.haml
.project_header
	.project_header_top
		.title
			%h1 Title:
		- if current_user == @project.user
			= link_to @project, method: :delete, data: {confirm: "Project:   '#{@project.name}'   willbe removed./nAre you sure?"} do
				.project_edit
					%i.icon-trash
			= link_to edit_project_path(@project) do
				.project_edit
					%i.icon-pencil-1
	.project_name_show
		%p= @project.name
	.star-rating{:"data-score"=> @avg_rating}
	%em= "#{@avg_rating}/5 of #{@commentz.size} comments"
	.project_header_bottom
		.project_back
			= link_to 'Back', projects_path
		.project_owner
			Created by:
			= @project.user.name
.project_content
	.project_content_image
		= image_tag @project.image.url("medium")
	.project_content_article
		= simple_format(@project.description)
.comments_main_container
	.comments_header
		.comments_tilte
			%h2 Comments
		.comment_creator
			= link_to new_project_comment_path(@project) do
				%i.icon-plus-squared
	.comments_content
		- if @comments.present?
			- @comments.each do |comment|
				.comment
					.comment_top
						.comment_author
							= comment.user.name
						.comment_time_stamps
							= comment.created_at.strftime('%d-%b-%Y at: %T')
						.comment_rating{:"data-score"=> comment.rating}
						- if comment.user == current_user
							= link_to project_comment_path(@project, comment), method: :delete, data: { confirm: "Comment will be removed. Are you sure?" } do
								.comment_edit_icon
									%i.icon-trash
							= link_to edit_project_comment_path(@project, comment) do
								.comment_edit_icon
									%i.icon-pencil-1
							
					.comment_bottom
						= simple_format(comment.content)
		- else
			Be the first one. Comment Now!
		= paginate @comments

app/views/projects/show2.html.erb
<div class="headerShowProj">
  <div class="showHeaderTop">
        <div class="title">          
          <h1>Title:</h1>
        </div>
        <% if current_user == @project.user %>
            <%= link_to @project, method: :delete, data: { confirm: "Project:    '#{@project.name}'       will be removed. Are you sure?" } do %>
              <div class="showIcon">                
                <i class="icon-trash"></i>
              </div>
            <% end %>
            <%= link_to edit_project_path(@project) do %>
              <div class="showIcon">                
                <i class="icon-pencil-1"></i>
              </div>
            <% end %>
            <div style="clear: both;"></div>
        <% end %>
  </div>
  <div class="showName">
    <p><%= @project.name %></p>
  </div>
  <div class="star-rating" data-score="<%= @avg_rating %>"></div>
  <em><%= "#{@avg_rating}/5 of #{@commentz.size} comments"%> </em>
  <div class="showHeaderBottom">
    <div class="showBack">
        <%= link_to 'Back', projects_path %>
    </div>
    <div class="showCreate">
      Created by: <%= @project.user.name %>
    </div>
    <div style="clear: both;"></div>
  </div>
</div>
<div class="contentShowProj">  
  <div class="showImage">    
    <%= image_tag @project.image.url("medium") %>
  </div>
  <div class="showArticle">
    <%= simple_format(@project.description) %>
  </div>
  <div style="clear: both; "></div>
</div>
<div class="commentsShowProj">  
  <div class="commentsHeader">    
    <div class="titleComments">
      <h2> Comments </h2>
    </div>
    <div class="creator" id="show">
      <%= link_to new_project_comment_path(@project) do %>
        <i class="icon-plus-squared"></i>
      <% end %>
    </div>
    <div style="clear: both;"></div>
  </div>
  <div class="commentsContent">
    <% if @comments.present? %>
      <% @comments.each do |comment| %>
        <div class="comment">
          <div class="commentTop">
            <div class="commentAuthor">
              <%= comment.user.name %>              
              </div>
            <div class="commentTimeStamps">
              <%= comment.created_at.strftime('%d-%b-%Y at: %T')%>
            </div>
            <div class="commentRating" data-score="<%= comment.rating %>"></div>
            <% if comment.user == current_user %>
              <%= link_to project_comment_path(@project, comment), method: :delete, data: {confirm: 'Are y sure ?'} do %>
                <div class="commentIcon">
                  <i class="icon-trash"></i>
                </div>
              <% end %>
              <%= link_to edit_project_comment_path(@project, comment) do %>
                <div class="commentIcon"><i class="icon-pencil-1"></i></div>
              <% end %>
            <% end %>
          </div>
          <div class="commentBottom">            
            <%= simple_format(comment.content) %>
          </div>
        </div>
        <div style="clear: both;"></div>
      <% end %>
    <% else %>
    Be the first one. Comment Now!
    <% end %>    
    <%= paginate @comments %>
  </div>
  </div>
</div>
<script>
  $('.star-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function(){
      return $(this).atrr('data-score');
    }
  });       
  $('.commentRating').raty({
    readOnly: true,
    path: '/assets',
    score: function(){
      return $(this).atrr('data-score');
    }
  });
</script>